name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4
      - name: build and create docker image
        run: sudo docker build . -t blaze:latest

      - name: Save Docker image
        run: docker save blaze:latest -o blaze.tar

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy to server
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" --delete ./blaze.tar ${{ secrets.SERVER }}:${{ secrets.SERVER_PATH }}

      - name: Load image on server
        run: ssh ${{ secrets.SERVER }} "sudo docker load -i ${{ secrets.SERVER_PATH }}/blaze.tar && docker run -d --rm --name blaze -p 80:8080 blaze:latest"
